"""added com[pany bname

Revision ID: 4110b979835f
Revises: 66d2a0ac95d7
Create Date: 2024-03-30 21:16:08.080671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4110b979835f'
down_revision = '66d2a0ac95d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('companyname', sa.String(length=30), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('companyname')

    # ### end Alembic commands ###
