"""added a column to save image_priority i.e default means it is the primary image  or name as uploaded

Revision ID: 466e56ed076a
Revises: 0c3824008054
Create Date: 2024-05-12 03:59:57.213014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '466e56ed076a'
down_revision = '0c3824008054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('default')

    # ### end Alembic commands ###
